### ISSUE TITLE
Support craftitems

### ISSUE THREAD

**Issue by tacotexmex** [minetest-mods/frame#4]
Currently, MTG binoculars can't be made to be compatible with frame because it's registered as a craftitem. I'm sure there are many more.

**Comment by sofar** [comment]
They probably need to be fixed like buckets in mtg. This mod supports them, but the right click code in the binocular mod probably doesn't delegate the right click properly.

**Comment by sofar** [comment]
https://github.com/minetest/minetest_game/issues/2241

**Comment by paramat** [comment]
@sofar @tacotexmex Isn't the fix adding binoculars and mapping kit to this list?
https://github.com/minetest-mods/frame/blob/fdac0292741217c663ec7f93404f8afe749f37d9/init.lua#L212
There are several craftitems already in that list.

**Comment by sofar** [comment]
yes, like, the bucket: `register_craftitem`.

https://github.com/minetest/minetest_game/blob/master/mods/bucket/init.lua#L113

**Comment by sofar** [comment]
The binuculars are definitely still missing from the list, yes.

**Comment by paramat** [comment]
Adding to the list fixed this, see https://github.com/minetest/minetest_game/issues/2241#issuecomment-432585690
